"""
Step 3: Transform extracted CSV files into word_bank INSERT SQL.
"""
import math
import os
import re
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import OUTPUT_DIR

SQL_OUTPUT = os.path.join(OUTPUT_DIR, "import_wordbank.sql")

# Max BNC rank for frequency normalization
MAX_BNC = 50000.0


def clean_definition(text: str, max_len: int = 500) -> str:
    """Take first line of definition, strip network tags, limit length."""
    if not text:
        return ""
    # Take first line
    first = text.split("\n")[0].strip()
    # Remove [network] / [医] / [化] etc. prefixes for cleaner output
    first = re.sub(r"^\[.*?\]\s*", "", first)
    if len(first) > max_len:
        first = first[:max_len]
    return first


def normalize_frequency(bnc: float) -> float:
    """Normalize BNC rank to [0, 1] range. Lower rank = higher frequency = closer to 1."""
    if not bnc or bnc <= 0:
        return 0.5
    # Logarithmic normalization
    freq = 1.0 - math.log(max(bnc, 1)) / math.log(MAX_BNC)
    return round(max(0.001, min(1.0, freq)), 3)


def collins_to_difficulty(collins: int) -> int:
    """Map Collins star rating to difficulty.
    Collins 5 = most common = difficulty 1
    Collins 1 = rarest = difficulty 5
    """
    if not collins or collins <= 0:
        return 3  # default medium
    return max(1, min(5, 6 - collins))


def escape_sql(text: str) -> str:
    """Escape single quotes for SQL."""
    if not text:
        return ""
    return text.replace("'", "''").replace("\\", "\\\\")


def main():
    levels = [
        "PRIMARY", "KET", "JUNIOR", "PET", "SENIOR",
        "CET4", "FCE", "CET6", "CAE", "TEM8",
    ]

    total_rows = 0
    sql_lines = [
        "-- VocabMaster word_bank import script",
        "-- Generated by 03_transform.py",
        "-- Total levels: 10",
        "",
        "SET NAMES utf8mb4;",
        "SET FOREIGN_KEY_CHECKS = 0;",
        "",
        "-- Clear existing data",
        "TRUNCATE TABLE word_bank;",
        "",
    ]

    for level_code in levels:
        csv_path = os.path.join(OUTPUT_DIR, f"words_{level_code}.csv")
        if not os.path.exists(csv_path):
            print(f"  SKIP {level_code}: file not found")
            continue

        df = pd.read_csv(csv_path, dtype=str)
        count = len(df)
        total_rows += count
        print(f"  {level_code}: {count} words")

        sql_lines.append(f"-- {level_code} ({count} words)")

        for _, row in df.iterrows():
            word = str(row.get("word", "")).strip()
            if not word:
                continue

            word_lower = word.lower()
            ipa_uk = escape_sql(str(row.get("phonetic", "") or "").strip())
            en_def = escape_sql(clean_definition(str(row.get("definition", "") or "")))
            zh_def = escape_sql(clean_definition(str(row.get("translation", "") or "")))

            # Skip if no Chinese definition
            if not zh_def:
                continue

            pos_val = escape_sql(str(row.get("pos", "") or "").split("/")[0].strip() if row.get("pos") else "")

            bnc_val = row.get("bnc", "")
            try:
                bnc_float = float(bnc_val) if bnc_val and str(bnc_val) != "nan" else 0
            except (ValueError, TypeError):
                bnc_float = 0
            frequency = normalize_frequency(bnc_float)

            collins_val = row.get("collins", 0)
            try:
                collins_int = int(float(collins_val)) if str(collins_val) not in ("", "nan", "None") else 0
            except (ValueError, TypeError):
                collins_int = 0
            difficulty = collins_to_difficulty(collins_int)

            sql_lines.append(
                f"INSERT INTO word_bank "
                f"(level_code, word, word_lower, ipa_uk, en_definition, zh_definition, "
                f"pos, frequency, difficulty, audit_status) VALUES ("
                f"'{level_code}', '{escape_sql(word)}', '{escape_sql(word_lower)}', "
                f"'{ipa_uk}', '{en_def}', '{zh_def}', "
                f"'{pos_val}', {frequency}, {difficulty}, 1);"
            )

        sql_lines.append("")

    sql_lines.append("SET FOREIGN_KEY_CHECKS = 1;")
    sql_lines.append("")

    # Write SQL file
    with open(SQL_OUTPUT, "w", encoding="utf-8") as f:
        f.write("\n".join(sql_lines))

    print(f"\nTotal: {total_rows} rows")
    print(f"SQL saved: {SQL_OUTPUT}")
    print(f"File size: {os.path.getsize(SQL_OUTPUT) / 1024 / 1024:.1f} MB")
    print("\nNext: python 04_import_to_db.py")


if __name__ == "__main__":
    main()
